### ISSUE TITLE
ReaderTest hangs indefinitely

### ISSUE THREAD

**Issue by PureTryOut** [nu-book/zxing-cpp#149] opened 2020-08-02 21:45 UTC
While running the latest tests from 1.1.0, it seems the `ReaderTest` hangs indefinitely.

This is being ran on Alpine Linux, if that matters.

**Comment by axxel** [comment] 2020-08-03 05:10
That is surprising (and unfortunate). Since the tests run just fine on my machine and also on all 4 CI, I will need your support in tracking that down. Can you provide the following information?

 * The last 3 lines of the console output you see in the state where it hangs.
 * The compiler name and exact version you are using.
 * One line of `make VERBOSE=1` output that shows the exact compiler options that are in use.

**Comment by PureTryOut** [comment] 2020-08-03 09:42
Last 3 lines of console output, I doubt this is actually useful information but sure :wink: 

```
Test project /home/bart/Documents/Git/alpine/aports/community/zxing-cpp/src/zxing-cpp-1.1.0/build
    Start 1: ZXingReaderTest
1/4 Test #1: ZXingReaderTest ..................   Passed    0.43 sec
    Start 2: ZXingWriterTest
2/4 Test #2: ZXingWriterTest ..................   Passed    0.01 sec
    Start 3: ReaderTest
```

Compiler: gcc 9.3.0

`make VERBOSE=1` output:
```
/usr/bin/g++ -Os -fomit-frame-pointer -Wl,--as-needed CMakeFiles/ReaderTest.dir/TestReaderMain.cpp.o CMakeFiles/ReaderTest.dir/ImageLoader.cpp.o CMakeFiles/ReaderTest.dir/Pdf417MultipleCodeReader.cpp.o CMakeFiles/ReaderTest.dir/QRCodeStructuredAppendReader.cpp.o CMakeFiles/ReaderTest.dir/BlackboxTestRunner.cpp.o -o ReaderTest  -Wl,-rpath,/home/bart/Documents/Git/alpine/aports/community/zxing-cpp/src/zxing-cpp-1.1.0/build/core ../../core/libZXing.so.1.1.0
```

Not sure if it matters, but Alpine Linux uses Musl (in this case version 1.2.0) rather than glibc.

**Comment by axxel** [comment] 2020-08-03 10:55
Thanks, but that does indeed not help much:
1. I meant the output of ReaderTest. You can get that with `ctest --verbose`
2. The make output you provided is a linker call. Could you please also send me one compile line (any .cpp file compilation, does not matter, which one).

**Comment by PureTryOut** [comment] 2020-08-03 13:15
Ah, of course there is a `--verbose` flag :tongue: 

```
test 3
    Start 3: ReaderTest

3: Test command: /home/bart/Documents/Git/alpine/aports/community/zxing-cpp/src/zxing-cpp-1.1.0/build/test/blackbox/ReaderTest "/home/bart/Documents/Git/alpine/aports/community/zxing-cpp/src/zxing-cpp-1.1.0/test/blackbox/../samples"
3: Test timeout computed to be: 10000000
3: aztec-1              @   0, total:  13, fast:  13 of  13, misread: 0 of 0, slow:  13 of  13, misread: 0 of 0, time: 4943 ms
3: aztec-1              @  90, total:  13, fast:  13 of  13, misread: 0 of 0, slow:  13 of  13, misread: 0 of 0, time: 5028 ms
3: aztec-1              @ 180, total:  13, fast:  13 of  13, misread: 0 of 0, slow:  13 of  13, misread: 0 of 0, time: 5387 ms
3: aztec-1              @ 270, total:  13, fast:  13 of  13, misread: 0 of 0, slow:  13 of  13, misread: 0 of 0, time: 6785 ms
3: aztec-2              @   0, total:  22, fast:   5 of   5, misread: 0 of 0, slow:   5 of   5, misread: 0 of 0, time: 17450 ms
3: aztec-2              @  90, total:  22, fast:   4 of   4, misread: 0 of 0, slow:   4 of   4, misread: 0 of 0, time: 17923 ms
3: aztec-2              @ 180, total:  22, fast:   6 of   6, misread: 0 of 0, slow:   6 of   6, misread: 0 of 0, time: 20619 ms
3: aztec-2              @ 270, total:  22, fast:   3 of   3, misread: 0 of 0, slow:   3 of   3, misread: 0 of 0, time: 17643 ms
```

It does seem to slowly go through this, just takes an awful lot of time. Maybe I didn't wait long enough and it isn't hanging indefinitely, but some form of speedup here would be nice.

As for compilation output, I guess this is what you want then:

```
cd /home/bart/Documents/Git/alpine/aports/community/zxing-cpp/src/zxing-cpp-1.1.0/build/core && /usr/bin/g++ -DZXing_EXPORTS -I/home/bart/Documents/Git/alpine/aports/community/zxing-cpp/src/zxing-cpp-1.1.0/core/src -Os -fomit-frame-pointer -fPIC -Wall -Wextra -Wno-missing-braces -ffloat-store -std=c++14 -o CMakeFiles/ZXing.dir/src/maxicode/MCBitMatrixParser.cpp.o -c /home/bart/Documents/Git/alpine/aports/community/zxing-cpp/src/zxing-cpp-1.1.0/core/src/maxicode/MCBitMatrixParser.cpp
```

**Comment by axxel** [comment] 2020-08-03 16:29
I think we are getting closer: the "-DNDEBUG" compiler option is missing (which makes it a debug-build, sort-of). This flag is automatically set by cmake for all but the "Debug" build. I guess you changed that by hand? This causes some debug file output to disc. I'll change that to require setting an explicit build option being set. Could you confirm that adding this flag makes the whole ReaderTest application finish in around 20s (on a reasonably modern CPU ;)).

**Comment by PureTryOut** [comment] 2020-08-03 23:09
On Alpine Linux we actually compile everything with the "None" build, as we found that other options overwrote our compiler options.

Adding `-DNDEBUG` to the CMake options made CMake say the variable was unused though :thinking:

**Comment by axxel** [comment] 2020-08-04 05:59
I was talking about the CMAKE_CXX_FLAGS variable to the string shows up at the compiler command line. Could you please
 * test if my recent commit fixes your issue and
 * post your cmake command line used to setup your build directory, so I can reproduce your findings?

**Comment by axxel** [comment] 2020-08-17 20:48
Since there has not been any feedback for 2 weeks I assume, my mentioned commit fixed the issue for you? If so, please close it. Thanks.

**Comment by axxel** [comment] 2020-09-04 09:36
Closing for lack of feedback from the OP.

**Closed by axxel** 2020-09-04 09:36 UTC

**Comment by PureTryOut** [comment] 2020-09-04 10:00
Oh, sorry, I missed this I think.

I added the commit locally to a 1.1.0 build, and although it seems to have shortened the delay, it's still quite long. Imo it's short enough now though, I didn't have the feeling it would never quit.

As for the CMake command line I use:

```
cmake -B build \
    -DCMAKE_BUILD_TYPE=None \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib  
cmake --build build
```

**Comment by axxel** [comment] 2020-09-07 12:16
Now I think I understand: you compile the code with no compiler optimizations whatsoever. The resulting code is simply dead-slow. You should not distribute (or use) zxing-cpp code without at least `-O2` optimization. I strongly recommend to drop the `-DCMAKE_BUILD_TYPE=None` line from your cmake call to get a "Release" build.

**Comment by PureTryOut** [comment] 2020-09-07 12:19
Well, no, that is not the case. We set `None` in CMake so it doesn't overwrite distro wide compiler options we set. `-O2` is set, just not by CMake but somewhere else in the build process.

**Comment by axxel** [comment] 2020-09-07 12:29
Could you please provide a compiler invocation command line (`make VERBOSE=1`) so I get to know exactly how the code is compiled?

**Comment by PureTryOut** [comment] 2020-09-07 12:37
For example:

```
[ 92%] Building CXX object example/CMakeFiles/ZXingReader.dir/ZXingReader.cpp.o
cd /home/bart/Documents/Git/alpine/aports/community/zxing-cpp/src/zxing-cpp-1.1.0/build/example && /usr/bin/g++  -I/home/bart/Documents/Git/alpine/aports/community/zxing-cpp/src/zxing-cpp-1.1.0/example/../thirdparty/stb -I/home/bart/Documents/Git/alpine/aports/community/zxing-cpp/src/zxing-cpp-1.1.0/core/src -Os -fomit-frame-pointer -std=c++11 -o CMakeFiles/ZXingReader.dir/ZXingReader.cpp.o -c /home/bart/Documents/Git/alpine/aports/community/zxing-cpp/src/zxing-cpp-1.1.0/example/ZXingReader.cpp
```

So ok, `-Os` instead of `-O2`.

**Comment by axxel** [comment] 2020-09-08 06:00
I get the following numbers on my system:
```
    | size | runtime
-Os | 1.3M |  20s
-O2 | 1.4M |  15s
```
(size of the libZXing.so, runtime of the ReaderTest part of a `ctest --verbose` call)

So depending on what you consider 'quite long' there either is or is not any issue with your build.

**Comment by PureTryOut** [comment] 2020-09-08 06:43
Interesting. Anyway like I mentioned, it already improved. From several minutes it went down to 20 or so seconds, which is good enough imo :wink: 

Thanks for the help!
