### ISSUE TITLE
Unrecognized QR code #2

### ISSUE THREAD

**Issue by workflowsguy** [nu-book/zxing-cpp#50] opened 2018-12-20 16:55 UTC
This is an example of a QR code that the Camera app in iOS will correctly decode, but neither `zbarimg` nor `scan_png` are detecting.

![qr code-test2](https://user-images.githubusercontent.com/12646357/50298773-3e5b3300-0480-11e9-873e-1ae8af2ef20f.png)

**Comment by axxel** [comment] 2020-06-09 11:19
This image is simply not a valid qr-code. won't fix.

**Closed by axxel** 2020-06-09 11:19 UTC

**Comment by workflowsguy** [comment] 2020-06-09 16:06
If this is not a valid QR Code, then how is it possible for IOS to correctly decode it and show the contents?

**Comment by axxel** [comment] 2020-06-09 16:33
I did not say that it is impossible to interpret this image. I said it does not conform to the QRCode specification. And since this is basically a duplicate of the issue #49, where I described how this could be pre-processed to make it work in zxing-cpp, I decided to close it.

**Comment by axxel** [comment] 2023-03-29 22:28
For whom it may concern: this image decodes out of the box with current HEAD (likely also with 2.0) when `tryDownscale` is enabled. Unclear when exactly this started to work.
