### ISSUE TITLE
zxing.readBarcodeFromPixmap is not a function

### ISSUE THREAD

**Issue by rgeraldporter** [nu-book/zxing-cpp#116] opened 2019-12-04 20:22 UTC
Hi, I've followed the instructions as given for a WebAssembly build, and lifted the HTML from the linked demo for the camera scanner, but am always getting the error `zxing.readBarcodeFromPixmap is not a function`

Has the function name for the reader changed since this example demo was last updated?

Example deployed here: https://build-ten-pink.now.sh

**Comment by huycn** [comment] 2019-12-04 20:55
Yes, that method was new. I've just added it this morning, https://github.com/nu-book/zxing-cpp/commit/3117a84a295d705dd157e46887463ebb50d4d833. Just hit pull gain and you will be ok.

**Comment by rgeraldporter** [comment] 2019-12-04 21:28
Hmm tried rebuilding a couple times, still giving the same error. Did confirm I had the latest pull. `console.log` still shows only the old exposed APIs though.

**Comment by rgeraldporter** [comment] 2019-12-04 21:42
Also tried clearing the `emcc --clear-cache` to see if that would help, but still seems to build without the method. Looking at the code I can't see why it's doing this. This is confusing.

```
 rob  ~ | projects | zxing-cpp | build  ? master ? 1 ? 1  git log
commit 85f9eeb4ce8f91d8fb732e1ab00243a6527bb414 (HEAD -> master, origin/master, origin/HEAD)
Merge: 3117a84 024155f
Author: Huy Cuong Nguyen <huycn@users.noreply.github.com>
Date:   Wed Dec 4 13:24:50 2019 -0500
```

<img width="464" alt="Screen Shot 2019-12-04 at 16 40 45" src="https://user-images.githubusercontent.com/955052/70183974-dca5d000-16b4-11ea-8bf8-52bfe367ffcd.png">

**Comment by huycn** [comment] 2019-12-04 22:01
Try to open your zxing.wasm in a text editor (the file is binary though), and search for `readBarcodeFromPixmap`, just to narrow down if it is a build or deployment issue.

**Comment by rgeraldporter** [comment] 2019-12-05 14:18
Yeah, it says "no results" when I search for that there.

**Comment by huycn** [comment] 2019-12-06 17:30
So it's build issue, likely a cache issue as you already guessed. The command you look for is maybe `emmake make clean`. Otherwise, as the build doesn't take time anyway, just remove everything and start over?

**Comment by axxel** [comment] 2020-06-04 07:34
trying to bring the WASM wrapper to the new CI-setup I ran into the same issue. I spent about a day hunting down that nasty problem. Only now stumbled upon this issue :-/. Has anyone of you found a viable fix for this?

I found the issue to be caused by the fact that the line `zxing = ZXing();` effectively assigns an 'empty' object because the MODULARIZEd module is only load on demand. According to some sample code, the way to go is
```
var zxing = ZXing().then(function(m){});
```
But that did not work either. What helped in the end was:
```
var zxing = ZXing().then(function(m){ zxing = m; });
```

If I don't hear any cleaner fix from you guys, I will update the documentation and add sample code based on this that works out of the box.

**Closed** 2020-06-04 16:55 UTC
