### ISSUE TITLE
Failed to detect image with low contrast

### ISSUE THREAD

**Issue by fang027** [nu-book/zxing-cpp#126] opened 2020-05-29 03:20 UTC
test image decode，this image failed，I don't choose  decode para，how should i do？thanks。
![zfb1](https://user-images.githubusercontent.com/18395986/83217469-6fc04e00-a19e-11ea-9148-f36f2abd941d.jpg)

**Comment by axxel** [comment] 2020-05-29 08:50
I had a look at your sample and the problem is the lack of contrast. The internal "HybridBinarizer" fails to reliably detect the green pixels as "black" (unfortunately). You can fix your issue in a number of ways:
 1. convert it to greyscale and make sure the green pixels are close to black
 1. use the GlobalHistogramBinarizer instead of the HybridBinarizer
 1. scale down your image to about 200x200 pixels

**Comment by axxel** [comment] 2022-04-16 18:55
This can be considered fixed with the new `DecodingHints::multiResolutionThreshold` option. See current `ZXingReader.cpp` on how to use the feature to detect this image.

**Closed by axxel** 2022-04-16 18:55 UTC
